name: portfolio

services:
  api:
    build: ./
    image: portfolio-api-image
    ports:
      - "5003:5003"
    networks:
      - portfolio-network-external
      - portfolio-network-internal
  vm:
    build: ./vm-container/
    image: portfolio-vm-image
    networks:
      - portfolio-network-internal
    volumes:
      - /mnt/storage-server0/sda3/portfolio/data/db.sqlite:/appdata/db.sqlite

networks:
  portfolio-network-external:
    driver: bridge
  portfolio-network-internal:
    driver: bridge
    internal: true