services:
  api:
    image: iyadelwy/portfolio-api-image:latest
    ports:
      - "5003:5003"
    networks:
      - grafana_loki
      - network-external
      - network-internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 100M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 60s
      timeout: 25s
      retries: 1
      start_period: 5s

  
  vm:
    image: iyadelwy/portfolio-vm-image:latest
    networks:
      - network-internal
    volumes:
      - /mnt/storage-server0/sda3/portfolio/data/db.sqlite:/appdata/db.sqlite
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.50"
          memory: 100M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 60s
      timeout: 20s
      retries: 1
      start_period: 5s



networks:
  network-external:
    driver: overlay
  network-internal:
    driver: overlay
    internal: true
  grafana_loki:
    external: true
